# 开发环境配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3307/garment_production?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: garment_user
    password: garment_pass_2024
  
  # Redis配置
  redis:
    host: localhost
    port: 6380
    password: garment_redis_2024

# 日志配置
logging:
  level:
    com.garment: debug
    org.springframework.security: info
    org.mybatis: debug