# Docker环境配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://mysql:3306/garment_production?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: garment_user
    password: garment_pass_2024
  
  # Redis配置
  redis:
    host: redis
    port: 6379
    password: garment_redis_2024

# 日志配置
logging:
  level:
    com.garment: info
    org.springframework.security: warn
    org.mybatis: warn