server:
  port: 8080

spring:
  application:
    name: garment-admin
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/garment_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: garment
    password: Garment@123
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  redis:
    host: 127.0.0.1
    port: 6380
    password: Redis@123
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.garment.admin.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.garment: debug
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/garment-admin.log

garment:
  jwt:
    secret: garment-production-system-secret-key-2024
    expiration: 86400000 # 24小时
    refresh-expiration: 604800000 # 7天
  
  # 文件上传配置
  file:
    upload-path: /data/garment/uploads/
    max-size: 10MB
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx
  
  # 系统配置
  system:
    name: 服装计件生产管理系统
    version: 1.0.0
    company: 优衣服装厂
    
  # 业务配置
  business:
    # 默认包大小配置
    bundle:
      default-size: 100
      min-size: 10
      max-size: 500
    
    # 质量系数配置
    quality:
      excellent-threshold: 0.98
      excellent-factor: 1.05
      normal-threshold: 0.95
      normal-factor: 1.00
      poor-threshold: 0.90
      poor-factor: 0.95
      bad-factor: 0.85
    
    # 打印配置
    print:
      default-printer-port: 9100
      template-path: /data/garment/templates/
      output-path: /data/garment/prints/